### ISSUE TITLE
Workspace for incoming files

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#10]
# Description

Files to be validated (plus schemas) should be stored in a location accessible by the validation jobs. If POSTing directly to the API, the files will be copied in the relevant place. It will be up to the integrations to calculate the exact files needed and copy them in the expected locations.

Ideally this would be a location directly accessible by the validation jobs. This could potentially be the same S3 output that we will use for reports (#4), but S3 would mean that we first need to upload the files to S3 and then stream from there to validate them.

# Tasks

- [ ] Investigate the best option from a cost/architecture perspective

# Estimates

{} effort in work days.

**Comment by amercader** [comment]
> Ideally this would be a location directly accessible by the validation jobs. This could potentially be the same S3 output that we will use for reports (#4), but S3 would mean that we first need to upload the files to S3 and then stream from there to validate them.

@pwalsh @roll any thoughts on this? Also keeping in mind https://github.com/frictionlessdata/goodtables.io/issues/6#issuecomment-257544831

**Comment by pwalsh** [comment]
I just love S3 :). It is so easy to manage, and ideal for stateless application design.

We can use a "real" filesystem as a service (e.g.: https://aws.amazon.com/efs/ ) if we design properly around it, but I prefer not.

Yes, S3 means that our jobs always call in files over HTTP - it means network latency etc. But we've designed tabulator (and therefore GoodTables) to work well in this case.

I prefer the benefits of the decoupled architecture, and to pay the extra time for streaming over the network.

**Comment by amercader** [comment]
OK, then I'll close that in favour of #8 as this is just part of the API
