### ISSUE TITLE
Deploy prototype [1.5d]

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#11]
# Description

Deploy all working components publicly

# Tasks

- [ ] Define hosting options for all components
- [ ] Create deploy scripts
- [ ] Deploy

# Estimates

1

**Comment by roll** [comment]
Also setup travis for tasks.

**Comment by roll** [comment]
@amercader 
what's recommended way to start flask server? gunicorn?

**Comment by pwalsh** [comment]
@amercader @roll can you please deploy this directly into the new kubernetes setup. Sync with Marko on #infra

**Comment by roll** [comment]
@pwalsh 
ok

**Comment by amercader** [comment]
@roll I don't have any preference, whatever you have experience with
