### ISSUE TITLE
Implement UI/X

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#116]
# Description

Requires #112

# Tasks

- [ ] Implement everything in #112

**Comment by amercader** [comment]
Let's discuss on Monday and clarify, but I guess this will mean

1. Implement @smth design in the Vue templates created in #92 
2. Separate client and server properly by rewriting all Flask endpoints to return JSON and make the client do the relevant requests.

**Comment by amercader** [comment]
We'll focus just on 1 for now (Implement Sam's design in the Vue templates)

**Comment by roll** [comment]
And there is #58 for 2.

**Comment by amercader** [comment]
Closing in favour of individual page issues.
