### ISSUE TITLE
Design goodtables badges

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#117]
# Description

Each **Source** in goodtables.io can have a badge that indicates if the data is valid or invalid, and the badge can link back to the *latest* **Job** Detail View for that **Source**.

It is likely we just go with the ecosystem and use [shields.io](http://shields.io) and a basic valid/invalid boolean state on the badges. But I want @smth to consider if he prefer an alternative, and @amercader to consider if there are badges we can should produce that are more informative.

# Tasks

- [ ] Decide on badge presentation
- [ ] Decide on additional badge options.

**Comment by amercader** [comment]
I'm confused. shields.io documentation does not do a great job of describing how to use / customize it.
Do we need to send a PR to shields.io adding support for GTIO? or redirect to one of [their URL](https://img.shields.io/badge/data-valid-brightgreen.svg) from our side? If the former to we need to implement a SVG endpoint ourselves or JSON one that they can pull?

**Comment by pwalsh** [comment]
@amercader no, it works as is. See the badges I created for issues and docs on https://github.com/openspending/os-viewer

**Comment by amercader** [comment]
But these are static right? We need the badge to change depending on the last job for that particular source. So as I understand it we can:

1. Have an endpoint `/github/badge/<org>/<repo>.svg` that checks status and redirects to the relevant status image from shields.io
2. Have an endpoint `/github/badge/<org>/<repo>.svg` that checks status and outputs a svg
3. Submit a PR to shields.io so `https://img.shields.io/goodtablesio/<integration>/<source>.svg` queries a GTIO endpoint and returns an svg directly.

**Comment by pwalsh** [comment]
@amercader right.

**Comment by amercader** [comment]
In terms of design I'll let @smth decide but I think that using the SVG returned by shields.io should be more than enough:

https://img.shields.io/badge/data-valid-green.svg?style=flat
https://img.shields.io/badge/data-valid-green.svg?style=flat-squared
https://img.shields.io/badge/data-invalid-red.svg?style=flat
https://img.shields.io/badge/data-invalid-red.svg?style=flat-squared

@smth If you think this design needs tweaking please add an estimate, if not I'll close this issue.

For implementation see #55

**Comment by amercader** [comment]
Also I think data: valid/invalid is the most useful for now. I can't think of any other useful or easy to convey in a badge.

**Comment by smth** [comment]
I have no reason to suggest that we don't use those shields.io ones.
