### ISSUE TITLE
Add support for datapackages

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#17]
# Overview

Current task configuration/descriptor doesn't support datapackages because of structure:
```
files:
settings:
```

# Ideas

We could introduce attribute `datapackages` (singular or plural?) wich will be mutually exclusive(?) with `files`:
```
datapackages:
settings:
```

If there will be more than 1 datapackages it will require a few tasks inside one build (based on current `goodtables` capabilities).

# Tasks

- [ ] add `datapackages` key to `goodtables.yml`
- [x] implement support on goodtables.py level - https://github.com/frictionlessdata/goodtables-py/issues/153
- [ ] tests

**Comment by roll** [comment]
@pwalsh 
@danfowler 
Is multiple datapackages per repository our use case?

**Comment by pwalsh** [comment]
@roll sure, why not?

**Comment by roll** [comment]
@pwalsh 
just to be sure (cc @amercader)

**Comment by pwalsh** [comment]
one or many data packages also ultimately represents some sort of file tree, and therefore can be reduced to the `files:` type of interface we use here anyway.

I might be good, as you said, to have:

```
datapackages:
files:
settings:
```

All possible as part of `goodtables.yml` (and not mutually exclusive). Whether this is then all just reduced to a single list of target files, or is a set of different jobs, is mostly just an implementation detail, with various pros and cons either way I suppose.

**Comment by amercader** [comment]
MVP if time, if not defer

**Comment by roll** [comment]
requires https://github.com/frictionlessdata/goodtables-py/issues/153

**Comment by roll** [comment]
@danfowler 
@amercader 
So Dan's preparing pilots with datapackage.json but this feature is not even for Alpha (mid of January). Is it correct?

**Comment by pwalsh** [comment]
@amercader assigned to you for scoping and estimates.

**Comment by amercader** [comment]
@roll can you add a mini spec and an estimate? You had a plan for this IIRC

**Comment by roll** [comment]
@amercader 
done :+1:
