### ISSUE TITLE
Finish Settings page implementation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#185]
# Overview

Two tabs: Github / Amazon S3
- GitHub
  - A button to sync the user account (ie get all user’s repos)
  - A list of repos, with the ones active on top, and a switch to activate or deactivate them
  - Ideally the repos would be filtered by organization to help navigate them but 
- Amazon S3
  - A list of active buckets, with name, link to jobs and option to remove / deactivate
  - A form to add new buckets, with three fields: name, access key id and secret access

# Tasks

- [ ] TBD

**Comment by roll** [comment]
@amercader 
Couldn't it be just `/settings` page? Like Travis has at `https://travis-ci.org/profile/<username>`

**Comment by amercader** [comment]
@roll sounds good
