### ISSUE TITLE
API should return error result if something goes wrong

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#19]
# Overview

TBD how it should be - thru error message etc

**Comment by amercader** [comment]
API response should be roughly:


```json
{
"id": "",
"status": "",
"created": "",
"finished": "",
..
either "report" or "error"

}
```

**Comment by roll** [comment]
@amercader 
So what's missing here after `test test test` PR?

**Comment by amercader** [comment]
This is done after #50

**Comment by pwalsh** [comment]
@roll still open?

**Comment by roll** [comment]
@pwalsh 
waiting review - https://github.com/frictionlessdata/goodtables.io/issues/54
