### ISSUE TITLE
Repos from organization account not accessible

### ISSUE THREAD

**Issue by ethanwhite** [frictionlessdata/goodtables.io#205]
I can't currently see repos from my organization account. The organization is https://github.com/weecology/ which I authorized it when granting access to goodtables.

Third-party access tab for weecology screenshot:

![screenshot from 2017-05-02 13-26-04](https://cloud.githubusercontent.com/assets/744427/25630453/3b119002-2f3b-11e7-94d6-1c7c9ec3e9d7.png)

Filtered results on goodtables.io:

![screenshot from 2017-05-02 13-26-29](https://cloud.githubusercontent.com/assets/744427/25630471/48e284ca-2f3b-11e7-9bb9-f7e3350816e5.png)

I have tried resyncing without success.

**Comment by amercader** [comment]
@roll can you prioritise this? This was caused by me reducing the oauth scopes requested. We need to find a middle ground between not asking too much and having everything we need to make the system work.

**Comment by roll** [comment]
@amercader 
At least I was able to reproduce it)
