### ISSUE TITLE
Setup migrations

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#21]
# Overview

As an example we could use - https://github.com/opentrials/collectors

**Comment by roll** [comment]
@amercader 
After this one we will be able to rebase on raw sqlalchemy

**Comment by amercader** [comment]
@roll I still think migrations are useful and we definitely should include them for Alpha but there's no need to migrate any dataset stuff to pure sqlalchemy, we can just nuke the db and start again (ie #21 can be done after #33)
