### ISSUE TITLE
Problem with github hook

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#211]
# Overview

Trying to validate this repo https://github.com/roll/causanatura-datos using http://goodtables.io/dashboard.

But github hook gets error 500 in response.

cc @amercader

**Comment by gabelula** [comment]
It also validates the first folder (Inspeccion) in the repo and not the rest. Not sure if it is related.

**Comment by roll** [comment]
@gabelula 
Thanks. I just was working on detecting all csv problem.

**Comment by amercader** [comment]
I think I might know what this is. I'll have a look asap

**Comment by amercader** [comment]
I wasn't able to reproduce this (500 error), the source worked for me: http://goodtables.io/github/amercader/causanatura-datos

See #212 for table detection issues.

Please reopen if still an issue.

**Comment by roll** [comment]
It's weird - not the same actions are OK for me too. May be it was an temporary servers outage.
