### ISSUE TITLE
Improve error descriptions on job reports

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#215]
We need meaningful titles and error descriptions, eg rather than `non-matching-header` in [here](http://goodtables.io/github/amercader/car-fuel-and-emissions) something more user friendly like what's shown on the [old Goodtables](http://goodtables.okfnlabs.org/reports?data_url=https%253A%252F%252Fgithub.com%252Famercader%252Fne-data-test%252Fraw%252Fmaster%252Fcouncillors-emails.csv&format=csv&encoding=&schema_url=), including the error [descriptions](http://goodtables.okfnlabs.org/help#structure_003).

I'm assuming this should be easy to port to the new reports regardless but let me know if you think otherwise @roll.

I'm not familiar with the background for these descriptions or where they should come from, whether from the old [goodtables-web repo](https://github.com/frictionlessdata/goodtables-web/tree/b59bfd2c7380284200409aed58fb0fdd56542e07/web/theme/templates/pages/help) or the newer [Data Quality Spec repo](https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json) but in any case it seems like it should be easy to integrate.

This should also include this small design issue:
- [ ] Close popups on next click (data-trigger="focus")

**Comment by pwalsh** [comment]
I think a markdown file per error, co-located with the data quality spec, would be ideal. could lazily read these md files when a user requests them. but any solution will be good.

**Comment by roll** [comment]
@pwalsh 
I thought we have `description` in `data-quality-spec` for it. I've started to fill it here - https://github.com/frictionlessdata/data-quality-spec/pull/12
