### ISSUE TITLE
Minor improvements on report

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#216]
- [x]  Error groups for in-row errors should show the headers row.

    ![zc5iafr](https://cloud.githubusercontent.com/assets/200230/26103451/6e5b632e-3a31-11e7-83fe-ae1e06668e2e.png)

- [x] Rows previewed don't show the correct rows (10, 100, 101, 102...) (see img above)
- [x] If we only show the first 10 errors we should display a message saying so.

**Comment by roll** [comment]
@amercader 
`Rows previewed don't show the correct rows (10, 100, 101, 102...) (see img above)`
Could you link the repo?

**Comment by amercader** [comment]
@roll 
https://goodtables.io/github/amercader/car-fuel-and-emissions
https://github.com/amercader/car-fuel-and-emissions
