### ISSUE TITLE
Validation task raises an exception on invalid datapackage

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#223]
# Overview

See - https://sentry.io/open-knowledge/goodtablesio-production/issues/277830991/

**Comment by amercader** [comment]
@roll What is the underlying issue here?

```
'gyear' is not one of ['string', 'number', 'integer', 'date', 'time', 'datetime', 'boolean', 'binary', 'object', 'geopoint', 'geojson', 'array', 'any']
```

Isn't gyear part of the spec? Or is this a pre-v1/v1 thing?

**Comment by ppKrauss** [comment]
Hi @amercader  

The *gyear* datatype is part of the spec, see http://specs.frictionlessdata.io/table-schema/#gyear

**Comment by roll** [comment]
@amercader 
There are two thing:
- the most important uncaught exception on invalid data package descriptor
- second is YES it's **pre-v1/v1 thing** - `gyear` has been introduced than renamed to `year`. But now it's again `gyear` because of https://github.com/frictionlessdata/specs/issues/420 (see task list)

@ppKrauss 
For now we just want to apologize for this situation with specs. We're working on fixing this confusion ASAP.

**Comment by amercader** [comment]
@ppKraus the first issue will be addressed soon in https://github.com/frictionlessdata/goodtables.io/issues/214

I totally agree the second is frustrating, and hopefully things will settle soon.

**Comment by ppKrauss** [comment]
Hi @amercader  and @roll , you are doing good job with Goodtables!
sorry my English,  only enforcing that seems a bug... I can wait the bug-fixing, and if  you need some help I can try.

**Comment by roll** [comment]
@pwalsh 
Just a note (may be you'll be interested) that's here we've run exactly in the problem specs-v1 is going to solve:
- https://raw.githubusercontent.com/datasets-br/state-codes/2e1fa020eed7ee58168d6c9e68bb59ddb8640512/datapackage.json is valid for `datapackage-py`
- but resource's schema is not valid Table Schema because it's not been dereferenced
- so I've missed that facts thinking that it's enough to check that data package descriptor is valid according to `datapackage-py`
