### ISSUE TITLE
Clarify terminology

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#24]
Now that we are early in the process it would be good to clarify how we name things (started from this [discussion](https://github.com/frictionlessdata/goodtables.io/pull/22#issuecomment-260945859)

* A **task** is an individual unit of work run by Celery. The most important one is the [main validation task](https://github.com/frictionlessdata/goodtables.io/blob/e34044ba15d596e9dcc543e661430841f908a71d/goodtablesio/tasks.py#L26).

* A **job** is comprised of one or more tasks, and includes the whole workflow for validating files depending on the input. For instance right now the GitHub plugin (see below) creates jobs that have two tasks (Task 1: Clone repo and get task desc -> Task 2: Validate). The job id is what the API uses to manage validation jobs (create, get, list). It is also a UUID but we can not rely on the ones created by celery, plugins must explicitly provide one so we can track the job status at different stages in the process.

* A **plugin** sits on top of the main goodtablesio library and integrates with an external service, creating jobs and doing the necessary steps to provide the options that the validation task requires.

@roll I also find task_conf and task_desc (introduced in #16) really confusing. What about:

* Task Conf -> Job Configuration (`job_conf`). `goodtables.yml` will grow to incorporate more stuff than simple validation configuration

* Task Desc -> Validation (Task) Configuration (`validation_conf`)

If you are happy with this I'll rename all the things

**Comment by roll** [comment]
@amercader 
`validation_conf` is great idea

What do you think about multiple jobs inside one build like travis do. Could it our case?

**Comment by amercader** [comment]
Maybe. I can't think of a use case now, do you have any potential examples?

In any case it sounds like a higher level concept that would be easy to add later on top of jobs.

**Comment by roll** [comment]
As for now multiple datapackages is not supported by library. So it's use case) But I suppose it will be great if we will be able to do not go into nested strucrure like travis always having `1 goodtables.yml hook -> 1 inspection -> 1 report`. It will simplify things a lot on all levels.

**Comment by amercader** [comment]
ok, so shall we focus on just jobs for now? (1 job -> 1 report)

It's good that you mention the `1 goodtables.yml hook` because we need a name for this entity. What about

* A **source type** is a kind of location where we can validate files from. This essentially maps to plugins (eg Github, S3, Dropbox)
* A **source** is an individual location for files to be validated with jobs, eg a specific repo, S3 bucket etc

Maybe we don't need to worry about these now but further down the line we will require some fields like that to easily display some UI like

My sources:
* Github repos
   - repo 1
   - repo 2
* Dropbox folders
   - folder 1
   - folder 2
....

**Comment by roll** [comment]
>  ok, so shall we focus on just jobs for now? (1 job -> 1 report)
:+1: 

About sources - it clashes with `source` from goodtables.yml. Projects?

**Comment by roll** [comment]
Also thing about naming - will our hooks be part of API like `api/github/hook`? Because it's still API? WDYT?

**Comment by roll** [comment]
@amercader 
https://github.com/frictionlessdata/goodtables.io/pull/23#issuecomment-260969881

Also we have to `report` here. I suppose top-level is a `result` (alongside with error or something)
