### ISSUE TITLE
All jobs I'm creating end with a fatal error

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/goodtables.io#253]
> Data Package "https://raw.githubusercontent.com/danfowler/collection/a627f1a4caf07911b341cd38d43f405d4e87322c/datapackage.json" has a loading error "__init__() got an unexpected keyword argument 'scheme'"

![screen shot 2017-07-13 at 15 50 48](https://user-images.githubusercontent.com/772616/28158225-403f26c6-67e3-11e7-8980-bd00e7d3824f.png)

**Comment by roll** [comment]
FIXED (`scheme` error) in https://github.com/frictionlessdata/goodtables.io/commit/2b75023ad3b7a715933069b344d68dacb705b609
