### ISSUE TITLE
Demo view design

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#257]
# Description

The [demo view](http://goodtables.io/demo) is now functionality complete and can completely replace the [old goodtables UI](http://goodtables.okfnlabs.org).

However, it is all just placed on the page as is. We need to spruce up the look and feel a bit, to the standards of the rest of the app.

# Tasks

- [ ] Minimal enhancements to improve the usability of the view

**Comment by roll** [comment]
@smth 
All styles for the demo is here - https://github.com/frictionlessdata/goodtables.io/blob/master/frontend/components/DemoForm.vue
It uses reusable component `goodtablesUI.Form` that has a root style `goodtables-ui-form`.

**Comment by smth** [comment]
Using the same template as the report http://p.smth.uk/goodtables/demo/

**Comment by pwalsh** [comment]
@smth looks really good!

**Comment by amercader** [comment]
Looks great :+1:

**Comment by roll** [comment]
DONE
