### ISSUE TITLE
Dashboard UI Design

### ISSUE THREAD

**Issue by smth** [frictionlessdata/goodtables.io#267]
Provide at a glance overview of "jobs", and required actions.

- [x] Design
- [x] Feedback
- [x] Mock up

**Comment by smth** [comment]
![gtio_app_02_dashboard_01](https://user-images.githubusercontent.com/1375708/31121546-8d2a83d0-a830-11e7-9836-7774e260b9b5.jpg)

![gtio_app_02_dashboard_01_no-errors](https://user-images.githubusercontent.com/1375708/31121569-aa44af40-a830-11e7-89c4-5d412f853a05.jpg)

**Comment by smth** [comment]
http://p.smth.uk/goodtables/dashboard/

**Comment by roll** [comment]
DONE
