### ISSUE TITLE
Jobs UI Design

### ISSUE THREAD

**Issue by smth** [frictionlessdata/goodtables.io#269]
Show each job, and its status, in reverse chronological order.

- [x] Design
- [x] Feedback
- [x] Mock up

**Comment by smth** [comment]
![gtio_app_02_jobs_01](https://user-images.githubusercontent.com/1375708/31122361-677f7f3e-a833-11e7-8814-aa2c2e9565c4.jpg)

**Comment by smth** [comment]
http://p.smth.uk/goodtables/jobs

**Comment by roll** [comment]
DONE
