### ISSUE TITLE
Fix problem with API response caching

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#27]
# Overview

It looks like requests like `/api/job/78be4c2c-3dad-4816-937a-2a2d1feb61ff` could be cached somewhere and after job is done still showing initial state.

# Notes

After @amercader investigation it looks like it's a `dataset` bug.

# Tasks

- [ ] implement https://github.com/frictionlessdata/goodtables.io/issues/33
- [ ] check this issue has been gone

**Comment by amercader** [comment]
Maybe related to dataset so probably related to #33

**Comment by pwalsh** [comment]
@amercader is this a bug or an enhancement? the way it is written, not sure. 

If a bug, then I'll put in Alpha, if just a (performance) enhancement, I'll put in Beta.

**Comment by roll** [comment]
@pwalsh 
could be merged with rebase on SQLAlchemy

**Comment by pwalsh** [comment]
@roll don't merge it, just describe it better.

**Comment by roll** [comment]
@amercader 
I'll re-assign you it you don't mind because this issue should be resolved by #33

**Comment by roll** [comment]
@amercader 
it's fixed right?

**Comment by roll** [comment]
NOT REPRODUCIBLE
