### ISSUE TITLE
404 UI Design

### ISSUE THREAD

**Issue by smth** [frictionlessdata/goodtables.io#271]
Explain that the page that the user is trying to reach does not exist. Provide a useful link to follow. Allow user to report an issue.

- [x] Design
- [ ] Feedback
- [x] Mock up

**Comment by smth** [comment]
http://p.smth.uk/goodtables/404/

**Comment by Stephen-Gates** [comment]
That's really clever - love it.

**Comment by roll** [comment]
DONE
