### ISSUE TITLE
Was working, but stop to work

### ISSUE THREAD

**Issue by ppKrauss** [frictionlessdata/goodtables.io#273]
At https://github.com/datasets-br/state-codes  ([goodtables](https://goodtables.io/github/datasets-br/state-codes))

The commit 20a54c669b179aa9cd401bf25b26689025229eef was working, so I reverted to it ... Now is not working.

----

PS: the other user was trying a lot of commits and no one worked... Is difficult to beginners use without a *local command goodtables-validator* for tests and previous validation.

**Comment by roll** [comment]
@ppKrauss 
The report provides an error message if you click on `Error Details`:
- Header in column 15 doesn't match field name "postalCode_range" in the schema

We improve our error detecting algorithms so it's expected that newer versions of `goodtables.io` are able to find more tabular errors.

---

About local validation - could you suggest for this user to try local `goodtables` command - https://github.com/frictionlessdata/goodtables-py#cli

**Comment by ppKrauss** [comment]
Thanks @roll , sorry, was it, an improve of "error detection algorithms", and now I corrected.

Thanks link for CLI (I forgot that you already showed it before), I send to users. 

Closing.
