### ISSUE TITLE
Recognize a Table Schema inside a JSON file

### ISSUE THREAD

**Issue by CharlesNepote** [frictionlessdata/goodtables.io#286]
First of all, thanks for the very good job.

goodtables.io is waiting for Schema as is: ``{ "fields": [ ] }``
Would it be possible to let goodtables.io recognize schemas inside other JSON files such as Data Packages or something else. Example: ``{ "schema": { "fields": [ ] } }``

See: http://try.goodtables.io/?source=https%3A%2F%2Fgist.githubusercontent.com%2FCharlesNepote%2F94983541b2ca3e84f29b616d1ffa29fa%2Fraw%2F674351f4b41ed0b581099378d38071c7a8dd711d%2Fprenom.csv&schema=https%3A%2F%2Fgist.githubusercontent.com%2FCharlesNepote%2F26126a30adddc1781cb652b2af164ea8%2Fraw%2F92ea63558c3d615ac21c5c31b286fa5f60cf7cd0%2Fprenom-schema.json&encoding=utf-8&apiJobId=b253eaee-d31c-49bb-9c64-328ee8d8f763

**Comment by vitorbaptista** [comment]
@CharlesNepote Thanks for the report, and sorry for the delay in responding. You can already add a URL to a data package, and it'll take the schema from it as you'd expect, and I just deployed a new version that also allow uploading the `datapackage.json` file directly. For now, only remote resources are validated, but I also want to add support for uploading a zipped data package that includes the data, so local resources could also be validated (issue #298)

**Comment by Stephen-Gates** [comment]
@vitorbaptista I assume this only works If the data package has one schema?

E.g. if the data package had two tables (e.g. the data and a lookup list of codes) would the schema for the first resource be used?

**Comment by vitorbaptista** [comment]
@Stephen-Gates This should work for any schema defined according to the spec. If there are multiple resources with multiple schemas, each one should be used to validate their corresponding resource. If that's not the case, it's a bug we must fix.

**Comment by Stephen-Gates** [comment]
Thanks @vitorbaptista will test in next few days
