### ISSUE TITLE
garbled content rendering on try.goodtables.io

### ISSUE THREAD

**Issue by serahrono** [frictionlessdata/goodtables.io#292]
With the new UI update, once a user clicks on the Validate button, content on try.goodtables.io looks like so:
<img width="1280" alt="try-goodtables-content-rendering-issue" src="https://user-images.githubusercontent.com/4550385/36029802-5c761104-0dad-11e8-8bf2-1b62acb0381f.png">
We need to fix
- [x] the width of the centre div
- [x] the width and margins on the rightmost div
- [x] Github icon rendering
- [x] validate button color
- [x] `what is goodtables.io?` text to explain the difference between try.goodtables.io and goodtables.io

**Comment by vitorbaptista** [comment]
@serahrono Could you try again? I couldn't reproduce the UI errors you found, but I pushed a new version and everything seems fine.

**Comment by serahrono** [comment]
All good, thanks @vitorbaptista!
