### ISSUE TITLE
github sync seems stuck

### ISSUE THREAD

**Issue by atmickle** [frictionlessdata/goodtables.io#316]
I'm not sure if this belongs in the issue tracker, but I added the goodtables app to my github account, and not the app just says "Syncing account. Please wait..". It's been a few hours now. I've logged in and out and used different browsers. Am I doing something wrong?

**Comment by MW3000** [comment]
I ran into the same problem. I cannot use the GoodTables.io service. It does not display any of my GitHub repositories. It only displays the "Syncing account. Please wait.." message.

**Comment by amercader** [comment]
Many apologies @atmickle for missing out your first report, and thanks @MW3000 for raising it again.
We've been migrating some of the underlying infrastructure and we obviously broke something on the way. We'll have a look as soon as we can.

**Comment by roll** [comment]
Sorry for that - it should be fixed now.

Please re-open if needed.

**Comment by MW3000** [comment]
Thank you @amercader and @roll. Now it works fine.
