### ISSUE TITLE
Add way to ignore files

### ISSUE THREAD

**Issue by jcolomb** [frictionlessdata/goodtables.io#321]
When cleansing data files, one still wants to keep the original file, as good data management practices,
there should therefore be a way to ignore these original files (or folders).

a way to got would be to ignore files with "_nottidy" in their name (or sth equivalent).

**Comment by augusto-herrmann** [comment]
Just add a `goodtables.yml` file specifying which files you want GoodTables to check. Then all other files should be ignored.

**Comment by roll** [comment]
Thanks @augusto-herrmann

It seems we have missed this question.

Yes, please use `goodtables.yml`.
