### ISSUE TITLE
error 502 "bad gateway"

### ISSUE THREAD

**Issue by vdubya** [frictionlessdata/goodtables.io#322]
The goodtables.io website appears to be giving a server error 502 "bad gateway" very frequently, but not every time. This started occurring a 2-3 weeks ago, but I did not experience it prior to that. Testing right now on Chrome v70.0.3538.102 64-bit on Windows 10, however all browsers/versions I have tried return the same result for me.

http://goodtables.io/jobs 

![image](https://user-images.githubusercontent.com/6257997/49049226-f9025900-f192-11e8-8102-c372e7a9aac1.png)

**Comment by vdubya** [comment]
1. Am I the only one receiving this error?

2. Can Cloudflare be disabled to test?

**Comment by roll** [comment]
@vdubya 
Sorry. It should be fixed by now
