### ISSUE TITLE
GitHub hook: username may not be available

### ISSUE THREAD

**Issue by AntoineAugusti** [frictionlessdata/goodtables.io#324]
Hello!

Happy new year. Thanks a lot for this service.

In [this GitHub project](https://github.com/AntoineAugusti/data-codes-sources-fr), I push commits automatically from CircleCI without a GitHub user. Because of this, the `username` key in the push payload received is not set and I get a 400 HTTP error when the hook is delivered.

![](https://puu.sh/Cq8Pw/caa8219d3a.png)

[See example hook payload](https://gist.github.com/AntoineAugusti/5c4eb02b7b59c55e1335ce10a63c723b).

If this happens, I propose to use the GitHub login of the sender instead. I've made a PR: #323

**Comment by roll** [comment]
Closed in #323
