### ISSUE TITLE
offline table review using goodtables.io command-line tool 

### ISSUE THREAD

**Issue by jhpoelen** [frictionlessdata/goodtables.io#339]
Hi!

Thanks for making the https://goodtables.io to help keep track of the quality of publicly available tables.

I deal with big collections of datasets and need to review many of them without having to rely on internet access. 

Do you have a command-line tool available to do things like:

```
$ goodtable https://example.org/somedatapackage > report_report.json
```
 
?

**Comment by roll** [comment]
@jdaviscooke 
Hi, sure - https://github.com/frictionlessdata/goodtables-py

**Comment by jhpoelen** [comment]
Thanks!
