### ISSUE TITLE
try.goodtables.io - Can't get a report from API. Reason: "Error: Reached maximum attemtps"

### ISSUE THREAD

**Issue by Nicholascop** [frictionlessdata/goodtables.io#360]
# Overview

try.goodtables.io used to work fine for validating files. Recently I've been getting the error message "Can't get a report from API. Reason: "Error: Reached maximum attemtps" when validating the same CSV file that worked vefore.

I use try.goodtables.io in my worjshops for researchers and academic librarians as an intro into what Goodtables can do.
![Screen Shot 2021-07-21 at 9 13 36 AM](https://user-images.githubusercontent.com/33733190/126496056-289b1e15-e96f-4605-8499-e3fb1bd59c14.png)

Is there anything that can be done to make the try.goodtables.io work again? Thank you.
---

Please preserve this line to notify @amercader (lead of this repository)

**Comment by roll** [comment]
Thanks @Nicholascop 

I'll investigate it

**Comment by roll** [comment]
Hi @Nicholascop,

It now works. Can you please try again and let me know if it still doesn't for you?

**Comment by Nicholascop** [comment]
Yes, it now works for me! Thank you very much.
