### ISSUE TITLE
Use the Github Tree API to infer files to validate

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#39]
TBD Rather than clone the whole repo, use the Tree API to get the layout of the repo so we can match it against goodtables.yml to decide which files to validate.

**Comment by roll** [comment]
Contents API also has this - https://developer.github.com/v3/repos/contents/#get-contents (limit is explicit - 1000 files per dir - pretty enough for us). May be it's a wrapper - http://github3py.readthedocs.io/en/master/repos.html#github3.repos.repo.Repository.contents

**Comment by pwalsh** [comment]
@amercader I'd really like to see this addressed for Alpha. Addressing could be WONTFIX, if you decide so, but we should lock down on best way to get data from GH.

**Comment by amercader** [comment]
I agree that this should be a priority.

To recap on options, from one of my previous comments:

1. Use the Tree API to get all paths in the repo + Match against goodtables.yml + Download them directly via https://raw.githubusercontent.com
2. Get the files changed or added from the push webhook payload + Match against goodtables.yml + Download them directly via https://raw.githubusercontent.com

2 is more efficient and does not require API calls but is perhaps slightly more complicated to implement. And it might be confusing for users (eg if only one CSV that was edited is validated in a repo with 10 other csvs).

**Comment by roll** [comment]
@amercader 
By downloading you mean pass to goodtables lib?

**Comment by pwalsh** [comment]
@amercader I agree that 2 is more efficient, but I think that 1 will give the least surprising user experience and be easiest to implement, as you said. We could open 2 on the backlog as an optimisation for after launch of the product, once we have enough volume of use to warrant it.

**Comment by roll** [comment]
Travis always runs all your tests. For example not changed file could be in different context (updated goodtables.yml or datapackage.json or schema.json etc)

**Comment by amercader** [comment]
+1 let's go with 1

**Comment by amercader** [comment]
The final implementation should use the user GH oatuh token to get the repo tree, so it's dependant on #69, but a first version can use the hardcoded auth that we are using now, so it is not blocked.

**Comment by amercader** [comment]
Recursive trees are the best option. If a library is needed I'd prefer [github3py](https://github3py.readthedocs.io) as it appears to have support for ETags
