### ISSUE TITLE
GitHub output for MVP

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#41]
Option 1

Badge on the README. We just need a new endpoint on the site that checks the last job against a certain repo (we would need to store the github repo identifier somewhere)

Option 2 

Status API that shows valid/invalid and link to the job page. For this we need an authorized user to post statuses to the repo. See below

Authorization options

Option 2.1

We test repos on the frictionlessdata organization and use one of our hardcoded API keys to post Statuses

Option 2.2 

We implement OAuth Github authorization so users can authorize repo access and use their API tokens

**Comment by amercader** [comment]
@pwalsh what should we aim for for MVP?

We eventually want to implement all of the above but we need to know what's needed for the MVP

**Comment by pwalsh** [comment]
@amercader I think I defined the requirements for the MVP quite well in https://github.com/frictionlessdata/goodtables.io/issues/5 What am I missing?
