### ISSUE TITLE
Document integration process for pilots

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#42]

**Comment by amercader** [comment]
As of now, the process to set up validation on a GitHub repo is the following:

* Choose a repository that contains tabular data files *inside the frictionlessdata organization*
* Go to *Settings* > *Webhooks*. Click on *Add Webhook*
* On *Payload URL*, enter: http://goodtables.oklabs.org/github/hook (leave the rest of fields as they are)

From this moment, once you start pushing to the master branch you should see the validation status next to the commit messages:

![dealwithit 1](https://cloud.githubusercontent.com/assets/200230/20802449/001ee8c4-b7e4-11e6-9e8b-b88390a659c7.png)

The statuses link to the full report on the prototype app.

Support for PRs, custom branches and proper authorisation is coming.

**Comment by pwalsh** [comment]
@amercader can you get this into the README, in a dedicated section, and then I guess we can close this issue.

**Comment by amercader** [comment]
Done
