### ISSUE TITLE
Support multiple branches and PRs

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#52]
# Overview

For now we always use `master` - https://github.com/frictionlessdata/goodtables.io/blob/master/goodtablesio/plugins/github/tasks.py#L31 (this function support `branch` kwarg)

**Comment by amercader** [comment]
We probably need to use the `ref` in `head`. Also check the `action` as we may not want to run it on all actions: https://gist.github.com/amercader/a918abaf61b7d15ec62423cc095cb300

**Comment by pwalsh** [comment]
@amercader can you do a mini-spec for this in a little more detail? I assume for a first pass, we want to run against any/all branches that exist, when any/all update.
