### ISSUE TITLE
User interface to login to GoodTables.io

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#63]
# Description

As a user, I want to be able to login to GoodTables.io, so I can manage my integrations and view reports on my data validation runs.

# Tasks

- [ ] Frontend logic and templates that hook into the #68 endpoints

**Comment by pwalsh** [comment]
Requires #68

**Comment by roll** [comment]
DONE
@amercader 
Assigning you and closing because you've already made it with #68
