### ISSUE TITLE
User interface to view jobs

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#66]
# Description

As a user, I want a list of all my previously run data validations, so that I can see my report history on GoodTables.io

- List of jobs
  - has relevant info like timestamp, integration backend, success/failure of latest, and more
  - can view whole history of reports for that job
  - has link to reports (the latest report, and also to all historical reports)

# Tasks

- [ ] TBD

**Comment by roll** [comment]
It should contain link in model between `job` and `user` or `user's github_repo/s3_folder` etc

**Comment by roll** [comment]
Also here we need to link all stuff to job we need for example `job configuration - goodtables.yml` (IF NEEDED).

**Comment by amercader** [comment]
See https://github.com/frictionlessdata/goodtables.io/pull/101 for details
