### ISSUE TITLE
User interface to view reports

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#67]
# Description

As a user, I want to view a report on a validation run, so I can assess the problems in my data (or feel happy that there are none!).

## Notes

We already have report templates for GoodTables:
- [First version, written as jinja in the first goodtables ui](https://github.com/frictionlessdata/goodtables-web/blob/master/web/theme/templates/pages/report.html#L80)
- [Second version, written as handlebars template](https://github.com/frictionlessdata/datapackagist/blob/master/datapackagist/src/scripts/components/ui/templates/validation-error-row.hbs#L1)
- [Third version, written as angular template](https://github.com/openspending/os-packager/blob/master/app/views/partials/modals/validation-results.html#L1)

All of the above implement the same UI, in different templating engines.
- Of course, we have the [GoodTables javascript client](https://github.com/frictionlessdata/goodtables-js) which needs to be updated for the new report object, and which the last two of the above depend on.

Obviously we need to change the template for the new report object, but essentially, the UI has been well designed for showing humans a good tables report, by @smth 

So, prepping these templates in [goodtables-js](https://github.com/frictionlessdata/goodtables-js) is a requirement to do this issue.

# Tasks

- [ ] Preparing the templates in goodtables-js
- [ ] Integrating them in GTIO

**Comment by roll** [comment]
@pwalsh 
@amercader 
I suppose should reformulated (the biggeat parr of work is done) and put to Beta

**Comment by amercader** [comment]
We'll create issues for the redesign
