### ISSUE TITLE
User and authorisation model

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#68]
We need a GTIO internal user model that allows us to identify users and enforce authorization. Plugin specific authorization should be linked to the GTIO users (eg oauth tokens for Github, access keys for S3, etc) so we need a way for plugins to attach information to users. 

For instance direct API calls should require an API key and we can enforce limits per user
On the UI, logged in Users could see their own jobs, set up new sources and authorize other plugins.

We can create our own users but allow to login with Github, Google etc and import the details (name and email)

Tasks:

- [x] Create SQLAlchemy model for users:
    User:
     * username
     * email
     * email_hash
     * admin (True/False)
     * ...
- [x] Login via Github, create user account if it doesn't exist yet
- [x] Logout

**Comment by amercader** [comment]
Focus on GitHub for Alpha first

**Comment by pwalsh** [comment]
no native login (ever, as far as @pwalsh is concerned). GH as auth provider is great for alpha and beta.
