### ISSUE TITLE
Basic, functional UI to see reports [1.5d]

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#7]
# Description

Very minimal design. Just a simple Bootstrap UI, showing the report for a given run.

For the MVP, this probably means:

- user clicks button/action on GitHub UI (from a pull request)
- that goes to a page, which pulls in the report from the static storage, and renders it in the UI

Lots more can be done later! We don't need much more than the above for the MVP.

# Tasks

- [x] Create an endpoint that renders a report template from the JSON report stored in S3

# Estimate

2

**Comment by pwalsh** [comment]
And I'm flagging now that we could even go without this for the very first MVP shipment, and link to the JSON file directly! ( but great if we don't have to do that :) )

**Comment by roll** [comment]
Static react page rendering JSON is 1 day work I suppose. GT JSON report could be too verbose for the user.

**Comment by pwalsh** [comment]
Well we already have report templates for GoodTables:

- [First version, written as ninja in the first goodtables ui](https://github.com/frictionlessdata/goodtables-web/blob/master/web/theme/templates/pages/report.html#L80)
- [Second version, written as handlebars template](https://github.com/frictionlessdata/datapackagist/blob/master/datapackagist/src/scripts/components/ui/templates/validation-error-row.hbs#L1)
- [Third version, written as angular template](https://github.com/openspending/os-packager/blob/master/app/views/partials/modals/validation-results.html#L1)

- Of course, we have the [GoodTables javascript client](https://github.com/frictionlessdata/goodtables-js) which needs to be updated for the new report object, and which the last two of the above depend on.

Obviously we need to change the template for the new report object, but essentially, the UI has been well designed for showing humans a good tables report, by @smth
