### ISSUE TITLE
Support skip rows in goodtables.yml

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#75]
# Overview

http://goodtables.oklabs.org/jobs/21ff2708-4c66-47af-8406-fcb8ab3a6aa1 (rows 2 and 3 are just commented)

**Comment by roll** [comment]
@danfowler 
@amercader 
@pwalsh 
I've designed options to skip rows (it could be introduced on tabulator level) but then I've just realized that it will not help for datapackages because this setting should be per file but datapackage.json encapsulates single file definitions. Don't specs have something like this?

**Comment by pwalsh** [comment]
Hi.

We should sync up on this and talk about the goals of the specs, and the different goals of tools like tabulator and goodtables, which are not limited to the concepts implemented in the specs.

At the moment, @rufuspollock and I want to be very careful about not turning the specs into a declarative ETL language. 

So things like skip rows simply do not belong there: as far as the specs are concerned, we expect good, clean data sources.

Certain tools might be more flexible in the face of reality, and some of these tools - goodtables and tabulator specifically - are perfectly valid and useful tools if the specs did not even exist.

**Comment by roll** [comment]
@pwalsh 
So to describe the situation (cc @rufuspollock).

We have file - https://github.com/frictionlessdata/ADB-User-Study/blob/master/metadata.tsv (it has commented rows 2 and 3)

1. Analyzing it as a single file we don't have problems (goodtable.yml):
```yml
files:
  - source: metadata.tsv
    ignore_rows: [2, 3]
```
2. Now consider we put this file as resource number 5 of some datapackage:
```yml
datapackages:
  - source: datapackage.json
```
All information about files inside the data container is encapsulated inside into descriptor. Ok, we could find some ways to add ingore rows somehow outside datapackage for concrete resource.

But this situation has led me to the thought that something like this on specs level couldn't be an ETL thing. We have things like `missingValue` so tihngs like `informationalRows: [2, 3]` (aka ignoreRowa) could make sense.

Because JTS is a schema for data and data could have meaningless rows. In JTS world this file - https://github.com/frictionlessdata/ADB-User-Study/blob/master/metadata.tsv - is invalid but publisher needs it. Ok I understand valid/invalid is a tools language but still..

Not proposing anything but thinking at loud.

**Comment by roll** [comment]
Related to this - https://github.com/frictionlessdata/specs/issues/326 - it's a row level metadata. For now we describe only field level metadata not touching rows. So may be it could fit for `Resource` spec.

**Comment by pwalsh** [comment]
@roll open up an issue on the specs tracker for rows to skip.
