### ISSUE TITLE
API to accept payloads from a frontend client

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#8]
# Description

There needs to be an API that accepts a payload, where a payload is a set of tabular files and a goodtables.yml spec for running data validations on those files. There could be many types of consumers for this API, but right now we are targeting our "official clients", and for the MVP GitHub is *the* official client.

Any files that need to be accessed by the validation jobs will be uploaded to S3 if necessary (it might make more sense that the integrations, eg #5 do it, in any case S3 will be the storage for source files as per https://github.com/frictionlessdata/goodtables.io/issues/10#issuecomment-257577637

Endpoints (TBD):

```
POST /task
GET /<user>/tasks
GET /task/<id>
...
```

# Tasks

- [ ] Define the API spec with the current requirements
- [ ] Implement the necessary endpoints

# Estimate

3

**Comment by roll** [comment]
@amercader 
Do you think goodtables.yml should be procesed inside the API or integrations (which one except github is going to use it?) should post already prepared files (task description)?

**Comment by pwalsh** [comment]
all of them will use goodtables.yml - why not?

**Comment by roll** [comment]
@pwalsh 
I mean how exactly github integration post reqeuest to the API could look like? It seems github integration anyway should extract files from repo based on gt.yml (we can't send all repo files I suppose?)?

**Comment by pwalsh** [comment]
@roll @amercader said there is a solution for that from GH via their API. That was one of my questions in moving away from git (where we have a map of the files in the directory)

**Comment by roll** [comment]
I suppose I've got it (what is current plan):
- integrations collect all project file urls and send them to API along with yml url
- API filters those urls based on yml (and yml base path) and prepare task payload

In this case integrations do know nothing about yml format and thus knowledge is encapsulated in API.

**Comment by amercader** [comment]
I think that the API should already received the filtered files from the integrations. There's no point in passing the yml for the API to filter if the integrations can already do it. Of course all integrations can share the same yml parsing library.

**Comment by amercader** [comment]
@roll see this for how to only get the files we need from github: https://github.com/frictionlessdata/goodtables.io/issues/2#issuecomment-255158332 Worst case scenario we might need to clone the whole thing, but I doubt it.

**Comment by amercader** [comment]
Basic API is in place, minus user specific endpoints, which depend on #5
