### ISSUE TITLE
Make database.user.email optional

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#84]
# Overview

If I hide my email on GibHub we gets SQL error.

**Comment by amercader** [comment]
This will make our life more difficult whenever we implement email notifications or require to communicate with the user but I guess that if they have that option on Github we need to deal with it in some way.

**Comment by roll** [comment]
@amercader 
Agreed but for now I suppose we just have to make it optional to fix situation with application error after registration (which I've got).
