### ISSUE TITLE
Validate/sync github hooks on repo syncing

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#90]
# Overview

For now we just look for `is_goodtables_hook` config option on a hook. But we also need to ensure that existent hooks correctly configured (e.g. if we will change domain we need to sync our hooks).

**Comment by pwalsh** [comment]
I don't understand this issue, so backlogging for now.

**Comment by amercader** [comment]
When we go through all user's repos to check if they have the GTIO hook active we are currently checking against a custom field in the metadata that we are adding when creating the hook (`is_goodtables_hook`). I guess that what @roll means is that we also check that the hook hasn't gone stale and uses an old domain for instance (when we move from the staging site to goodtables.io). It's fine for the backlog for now.

**Comment by roll** [comment]
@amercader 
We need to prioritize this  because now e.g. we could have `stating.goodtables.io` hooks wich will be preventing creating hooks for `goodtables.io`.

**Comment by amercader** [comment]
@roll yes, this is an issue now. If we can have at least a simple check against staging/production that would be great (store the domain name in the hook config?)
