### ISSUE TITLE
Bad SQL query could break db session for further requests

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#97]
# Overview

```
goodtables-web-3491746301-vafrr -- sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.IntegrityError) null value in column "email" violates not-null constraint
```

It will be fixed by #84 for now but we better investigate how to prevent errors like this for the future because SQL error happens (it shouldn't break the whole application requiring restart).

# Reference

http://docs.sqlalchemy.org/en/latest/faq/sessions.html#this-session-s-transaction-has-been-rolled-back-due-to-a-previous-exception-during-flush-or-similar

# Ideas

- add flask/celery error handler
- http://stackoverflow.com/questions/33284334/how-to-make-flask-sqlalchemy-automatically-rollback-the-session-if-an-exception/33284980#33284980

**Comment by roll** [comment]
@amercader 
I'm really stuck with it) Reading thru all implicit things SA doing with transaction/connections.. So for now I see 2 things:
- we anyway should wrap all db mutations in try-catch with rollback
- as a last call I'm adding `session.rollback` to app and celery unhandled error wrappers

**Comment by amercader** [comment]
We definitely don't want to wrap everything in try/except (from the docs:

> This is not to say that you need to put try/except blocks all throughout your application - on the contrary, this would be a terrible idea. You should architect your application such that there is one (or few) point(s) of “framing” around session operations.

A context manager like the one shown at the end of this section sounds like the best approach: http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it

Do you have the full traceback though? Including the first original exception and the second one.

**Comment by roll** [comment]
@amercader
What's the difference with this context manager and without? With it it still returns to the user internal server error. We should catch it anyway.

Second listing from your link seems pythonic way to go - explicitly catch exceptions, rollback and do app level fallback in the catch block.

So I don't see a problem with try-catching not safe mutating operations - it's a pretty good practice anyway. And explicit rollback seems too - there is already enough magic in sqlalchemy)
