### ISSUE TITLE
Decide/improve logging

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#98]
# Overview

For now it's not sure is current situation with logging on deis cluster acceptable or not so we should:
- review the situation
- improve logging if needed (like rebase on papertrail etc)

**Comment by roll** [comment]
Gunicorn to syslog - http://docs.gunicorn.org/en/stable/settings.html#syslog-add

**Comment by roll** [comment]
Celery to syslog? - http://oriolrius.cat/blog/2013/09/06/celery-logs-through-syslog/

**Comment by pwalsh** [comment]
Closed for #119
